swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: localhost:3000

basePath: /
schemes:
  - http
paths:
  /search:
    post:
      summary: Returns API search response or finds data in local database
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: userSrc 
          type: string
      responses:
        200:
          description: OK
  
  /search/{id}: 
    get:
      summary: Returns detailed response about a show or a movie 
      description: If user is reading detailed information about show or movie for the first time, the information is saved to a local database.
      parameters:
        - in: path
          name: id
          required: true
          type: string
          minimum: 1
          description: Parameter description in Markdown.
      produces:
        - application/json

      responses:
        200:
          description: ok
  
  /quicksearch: 
    post:
      summary: Suggests a movie or a show while typing into searchbar
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: userSrc 
          type: string
      responses:
        200:
          description: OK